server {
    listen 80;
    index index.php index.html;

    # Set the document root to the public directory of the Laravel application
    root /var/www/public;
    # Disable server tokens to prevent revealing the nginx version
    server_tokens off;

    location / {
        # Try to serve the requested URI as a file, and if it doesn't exist, pass the request
        try_files $uri /index.php?$args;
    }

    # Setting up the location block for PHP files to be processed by the FastCGI server
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}